name: compass
channels:
  - compass
dependencies:
  - python
  - astropy
  - docopt
  - h5py
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pyqtgraph
  - scipy
  - pytables
  - tabulate
  - tqdm
  - compass
  - coverage
  - pytest-cov
  - pytest-html
  - pytest-metadata
